<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into craft/config/db.php, and make your change there.
 */
return array(
  '*' => array(
    'server' => 'localhost',
    'database' => 'craft',
    'tablePrefix' => 'craft',
  ),

  'localhost' => array(
    'user' => 'root',
    'password' => 'root',
	/**
	 * If this is set, then the CLI connection string (used for yiic) will
	 * connect to the Unix socket, instead of the server and port. If this is
	 * specified, then 'server' and 'port' settings are ignored.
	 */
	'unixSocket' => '/Applications/MAMP/tmp/mysql/mysql.sock',
  ),

  // Use IP of your droplet and MySQL credentials of a user you created
  '104.236.161.221' => array(
    'user' => 'craftgod',
    'password' => '6014Pasco**',
  )
); 

